### ISSUE TITLE
Question more than an issue.

### ISSUE THREAD

**Issue by joshhartmann** [newbthenewbd/grav-plugin-tinymce-editor#12]
How do I add the TinyMCE to a custom text field in Grav?

**Comment by joshhartmann** [comment]
Nvm I found the answer.

Add "type: markdown" to your blueprint .yaml e,g,

header.custom.textField:
          type: markdown
          label: Product Description
          rows: 10

**Comment by newbthenewbd** [comment]
Actually, I haven't tested this and don't currently have time to, however, according to #11, `type: tinymce` should do the job.
