### ISSUE TITLE
How to add HTML5 tags in the editor?

### ISSUE THREAD

**Issue by 5minutesturkish** [newbthenewbd/grav-plugin-tinymce-editor#15]
I try to add HTML5 tags in the editor, by following this example: https://www.tinymce.com/docs/demo/format-html5/. 

In the plugin option page I added «visualblocks» in plugins section, then created new row and paste «section | article», but these options did not appear in the editor.

What have I done wrong?

**Comment by newbthenewbd** [comment]
The options `section` and `article` do not exist. Instead, `visualblocks` should be put into the new row. To display the blocks by default, a parameter called `visualblocks_default_state` should be added under Parameters, and set to `true`.

On another note, there seems to be some anomaly as to how the new Grav admin plugin theme handles noncollapsible lists - the values go invisible right after saving them...
