### ISSUE TITLE
convert from Markdown to TinyMCE html (and vice versa)

### ISSUE THREAD

**Issue by ComputingFroggy** [newbthenewbd/grav-plugin-tinymce-editor#20]
Hi,
I am just testing Grav with TinyMCE (as Markdown is not an option for end users). I can see a potential problem: it seems there's no way to convert from Markdown to HTML. So if one already starts using Grav, it's going complicated to start using TinyMCE.
In the same line of thought, if one decides to stop using TinyMCE, is there a way to switch back the pages to Markdown ?

I could not find any mention about that, which I find surprising as it is quite critical, so I might have missed something.

**Comment by newbthenewbd** [comment]
While no converter (aside from the built-in Markdown parser) is available, disabling Markdown parsing is not a necessary step for the plugin to work, and Grav's Markdown parser integrates quite well with HTML. The other way around, it also works, as TinyMCE isn't required for HTML code to work in Grav.

Therefore, the only issue left is how messy the page source becomes after a few such switches, and I deem that hardly possible to automatically fix, as Markdown has highly limited syntax compared to HTML, plus there are many Grav-specific Markdown extensions that would somehow have to be supported.
