### ISSUE TITLE
{{ "lol" }}

### ISSUE THREAD

**Issue by Razunter** [newbthenewbd/grav-plugin-tinymce-editor#27]
there is {{ "lol" }} in the code...

https://github.com/newbthenewbd/grav-plugin-tinymce-editor/commit/2480b231ed8a56b5dc4544e29c3b1b52b454b64e

templates/forms/fields/tinymce/tinymce.html.twig

**Comment by newbthenewbd** [comment]
Remove one overlooked debug check, another one appears, and even sillier than the previous one... :smile:

Thanks for reporting, will fix ASAP!

**Comment by newbthenewbd** [comment]
Fixed in v1.2.3... Hopefully! :upside_down_face:
