### ISSUE TITLE
Error Trying to Change Folder Name

### ISSUE THREAD

**Issue by thekenshow** [newbthenewbd/grav-plugin-tinymce-editor#30]
Hi,

I get the following error when trying to change the folder name for a copied page using the Admin:

```
 Whoops \ Exception \ ErrorException (E_WARNING)
Use of undefined constant LIBXML_HTML_NODEFDTD - assumed 'LIBXML_HTML_NODEFDTD' (this will throw an Error in a future version of PHP)
```

Pointing to `/user/plugins/tinymce-editor/tinymce-editor.php:17`.

**Comment by newbthenewbd** [comment]
Whoa, so there are still distributions with PHP 5.6.4 or higher, yet [with libxml lower than 2.7.8](https://secure.php.net/manual/en/libxml.constants.php)? Will try to push a patch ASAP.

Thanks for reporting!

**Comment by thekenshow** [comment]
Hi - tested and confirmed OK, thanks!

--
Cheers
Ken

https://kendow.com | +1 (519) 270-5338

Nobody's smart enough to be wrong 100% of the time.
- Ken Wilber
