### ISSUE TITLE
404 Uncaught ReferenceError: tinymce is not defined

### ISSUE THREAD

**Issue by Genenenenaam** [newbthenewbd/grav-plugin-tinymce-editor#32]
**Where does the error take place:**

Grav allows you to add extra fields in your site configuration tab:
![schermafbeelding 2019-02-15 om 09 57 52](https://user-images.githubusercontent.com/20650976/52845762-362e1580-3108-11e9-9f14-0670b8958c6e.png)

To do this your have to make an extra yaml file in 'user -> blueprints -> config -> newfile.yaml' (in the preview this file is called pau.yaml)
<img width="172" alt="schermafbeelding 2019-02-15 om 10 00 29" src="https://user-images.githubusercontent.com/20650976/52845911-8f964480-3108-11e9-9d11-2d4a9700e505.png">

if you define fields as `type: tinymce` you get the error `Uncaught ReferenceError: tinymce is not defined`
(next: Preview of the defined fields. Last field is defined as tinymce)
<img width="351" alt="schermafbeelding 2019-02-15 om 10 06 37" src="https://user-images.githubusercontent.com/20650976/52846392-c456cb80-3109-11e9-8f6f-9d1c741527cf.png">
(next: Preview of how the tinymce field renders in admin)
![schermafbeelding 2019-02-15 om 10 12 28](https://user-images.githubusercontent.com/20650976/52846574-3fb87d00-310a-11e9-8344-591a44b60f46.png)

**What did i already try**
- updated Grav and the plugin to latest version
- clean install with only the tinymce plugin added
- Tinymce plugin does work when used for 'Pages / templates' blueprints, but not in config

(Preview installed plugins and versions:)
![schermafbeelding 2019-02-15 om 10 22 08](https://user-images.githubusercontent.com/20650976/52847125-a5f1cf80-310b-11e9-9b3b-8dc4fbb5ad40.png)

**Comment by newbthenewbd** [comment]
I suppose that's how prematurely optimizing the plugin to load TinyMCE only when pages are being edited ends... :upside_down_face:

Fixed in v1.2.6, hopefully. Thanks for reporting!
