### ISSUE TITLE
Drag & Drop from page media not working

### ISSUE THREAD

**Issue by anjoclaudio** [newbthenewbd/grav-plugin-tinymce-editor#33]
I've added paste_data_images parameter but when dragging and dropping an image from page media it only creates a markdown image link. Drag & Drop from elsewhere works fine otherwise.

**Comment by Romarain** [comment]
@anjoclaudio I have the same problem. I found, by inspecting the code with the dedicated button on the TinyMCE bar, **that the plugin was wrapping the markdown of images in <div>**. So, it means that the markdown can't be processed, due to the HTML precedence.

The plugin should not generate those root blocks, especially if we have :
```
  -
    name: forced_root_block
    value: 'false'
```
But it does. :(

**Comment by newbthenewbd** [comment]
Dragging and dropping page media into the editor is scheduled to appear as a feature in the soon-to-be release of the plugin - it has now, amongst many other things, been implemented in the latest development version.

If it's not a problem, please install that version [as described here](https://github.com/newbthenewbd/grav-plugin-tinymce-editor#manual-installation) and give feedback, just to make sure that the ~~horrible awful hacks~~ javascript code added to perform that job works right before we call it a release.

Thanks!

**Comment by Zajozor** [comment]
I know this is an old issue - but if this project is not abandoned, could this be fixed please ?

I installed the latest development version and when dragndropping image from the media section to the editor, it shows "insert link" dialog.
What i'd expect is an insert media dialog with images..

<img width="490" alt="CleanShot 2021-01-07 at 10 48 59@2x" src="https://user-images.githubusercontent.com/1835434/103877972-132ef500-50d6-11eb-8c1d-ee9301b1adcb.png">

if its an easy fix and you can guide me, im open to submiting a PR.

thanks :)

**Comment by newbthenewbd** [comment]
Yup, to say the least it's about time to actually find a little time and polish up all the changes for release (or actually, more like two releases - it doesn't look like all the changes will be possible to implement without a slight deprecation).

Thanks for the push - a couple just as important ones that apparently popped up lately weren't even put in my notifications for some reason...

**Comment by newbthenewbd** [comment]
Fixed in v1.3.0 - hopefully. :slightly_smiling_face:
