### ISSUE TITLE
[QUESTION] TinyMCE on modular section

### ISSUE THREAD

**Issue by dorothywasright** [newbthenewbd/grav-plugin-tinymce-editor#46]
Hi,
is it possibile to enable the editor on the modular section and in the admin pages?

Thanks ✌

**Comment by newbthenewbd** [comment]
Whoops, sincere apologies, overlooked this one badly...

To the best of my knowledge, it should be possible to use TinyMCE anywhere with the use of this plugin, by specifying `type: tinymce` in the relevant blueprints, in lieu of `type: editor`.

You're welcome to open a new issue (and I will sure try to respond before forgetting about it this time :upside_down_face:) in case this remains a problem - for now, closing.
