### ISSUE TITLE
languages.yaml contains a double key and crashes

### ISSUE THREAD

**Issue by rcheetah** [newbthenewbd/grav-plugin-tinymce-editor#54]
The file `languages.yaml` contains a double key `WHITELIST_HELP` and crashes grav.

```
    WHITELIST_HELP: The collection of pages to enable TinyMCE on.
    BLACKLIST: "Blacklist"
    WHITELIST_HELP: The collection of pages to disable TinyMCE on, even if they are whitelisted.
```

Delete first line and everything works again.

**Comment by newbthenewbd** [comment]
Fixed in v1.3.2. That was a silly one. :upside_down_face:

Thanks for reporting!
