### ISSUE TITLE
Height Parameter Ignored?

### ISSUE THREAD

**Issue by thekenshow** [newbthenewbd/grav-plugin-tinymce-editor#9]
First off, thanks - this will make clients very happy!

I'd like to change the default height of the editing area, but adding 'height: 600' to my tinymce-editor.yaml file has no effect. I'm able to toggle the existing 'statusbar' on and off, so the .yaml file is being read.

I tried adding 'elementpath: false', and that also had no effect. Should this plugin support all of the [TinyMCE appearance parameters](https://www.tinymce.com/docs/configure/editor-appearance), or only those in the default tinymce-editor.yaml file that comes with the plugin?

**Comment by newbthenewbd** [comment]
For an additional TinyMCE parameter to actually work, it should be appended to the `parameters` field, like this:
```
parameters:
  -
    name: fontsize_formats
    value: '6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 20pt 22pt 24pt 26pt 28pt 32pt 36pt 40pt 44pt 48pt 54pt 60pt 66pt 72pt 80pt 88pt 96pt'
  -
    name: paste_data_images
    value: '1'
  -
    name: height
    value: '600'
  -
    name: elementpath
    value: 'false'
```
According to a quick test that I've done, both parameters work with no issues when appended like that.

Merry Christmas!

**Comment by thekenshow** [comment]
Ah, fantastic - thanks! Merry Christmas to you 🎄
